### ISSUE TITLE
Feature request:  Return response in object, array or json

### ISSUE THREAD

**Issue by yadakhov** [nbobtc/bitcoind-php#11]
Currently the responses are returned as PHP objects.  Example: `$object->info`  I think it would be useful to have an option in the client to return responses as array.

I prefer responses to be returned as array.  Example: `$object['info']`

Returning as json would be useful as well, since this is what bitcoind returns.

**Comment by JoshuaEstes** [comment]
This should be resolved in the 2.x branch, there's still a little more I need to do with testing and such. It will return the output as a string which you can run `json_decode` on it to get an object or array.

I'm still working on the details, but have some documentation in the readme.

**Comment by JoshuaEstes** [comment]
Check out the documentation of the new 2.x version. That should solve the issue. If it doesn't let me know. Thanks!

**Comment by yadakhov** [comment]
Thanks.  It looks good.
