### ISSUE TITLE
incompatible with psr/http-message current version

### ISSUE THREAD

**Issue by ghost** [nbobtc/bitcoind-php#16]
Just installed with composer (as a vendor in a cakephp 3 project), received this error at the first try: 
Fatal error: Declaration of Nbobtc\Http\Message\Message::withBody() must be compatible with Psr\Http\Message\MessageInterface::withBody(Psr\Http\Message\StreamInterface $body) in ****\vendor\nbobtc\bitcoind-php\src\Http\Message\Message.php on line 18

the psr http-message module was updated recently, maybe it was a major update. There is no streamableinterface any more as I see, but could not resolve the error by trying to make it compatible (renaming and stuff), just more errors occured..

**Comment by JoshuaEstes** [comment]
Good catch, thanks for letting me know. I'll try to find some time this weekend to get this updated.

**Comment by JoshuaEstes** [comment]
Fixed with release 2.0.2
