### ISSUE TITLE
catch exception

### ISSUE THREAD

**Issue by ghost** [nbobtc/bitcoind-php#27]
How to catch an exception which for example may occur when bitcoind is offline?
Wasn't able to solve this by using:

private function getAddress(){

    //...prepare connection
    try{
        $response = $client->sendCommand($command);
        return json_decode($response->getBody()->getContents());
    }
    catch(Exception $e){
        return json_encode([
            'errors' => 'server offline',
            ]);
    }

**Comment by irfankazi56** [comment]
Even I am unable to handle exception like when there is connection issue or server is down. I want to generate an error when connection fails. Can anyone help?

**Comment by irfankazi56** [comment]
Did you solve this issue?
